name: Mirroring

on: [push]

jobs:
  to_github:
    runs-on: ubuntu-18.04
    if: ${{ github.repository == 'neru-pagamentos/backend' }}
    steps:                                              # <-- must use actions/checkout@v1 before mirroring!
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:neru-pagamentos/backend-solutions.git
        ssh_private_key:                                # <-- use 'secrets' to pass credential information.
          ${{ secrets.PRIVATE_KEY }}
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: "Delete branch"
      if:  ${{ steps.extract_branch.outputs.branch != 'master' }}
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{github.token}}
        branches: ${{ steps.extract_branch.outputs.branch }}
